/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSchedulesRouteImport } from './routes/dashboard.schedules'
import { Route as DashboardPatientsRouteImport } from './routes/dashboard.patients'
import { Route as DashboardOutcomesRouteImport } from './routes/dashboard.outcomes'
import { Route as DashboardKnowledgeRouteImport } from './routes/dashboard.knowledge'
import { Route as DashboardDoctorsRouteImport } from './routes/dashboard.doctors'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard.campaigns'
import { Route as DashboardCallsRouteImport } from './routes/dashboard.calls'
import { Route as DashboardPatientsIndexRouteImport } from './routes/dashboard.patients.index'
import { Route as DashboardCampaignsIndexRouteImport } from './routes/dashboard.campaigns.index'
import { Route as DashboardPatientsListIdRouteImport } from './routes/dashboard.patients.$listId'
import { Route as DashboardCampaignsCampaignIdRouteImport } from './routes/dashboard.campaigns.$campaignId'
import { Route as ApiHmisSyncRouteImport } from './routes/api.hmis.sync'
import { Route as ApiElevenlabsTtsRouteImport } from './routes/api.elevenlabs.tts'
import { Route as ApiElevenlabsScribeTokenRouteImport } from './routes/api.elevenlabs.scribe-token'
import { Route as ApiCallsStartPlivoRouteImport } from './routes/api.calls.start-plivo'
import { Route as ApiCallsStartRouteImport } from './routes/api.calls.start'
import { Route as ApiCallsRecordingRouteImport } from './routes/api.calls.recording'
import { Route as ApiCallsHangupRouteImport } from './routes/api.calls.hangup'
import { Route as ApiCallsCleanupRouteImport } from './routes/api.calls.cleanup'
import { Route as ApiCallsBridgeStatusRouteImport } from './routes/api.calls.bridge-status'
import { Route as ApiCallsBackfillRecordingRouteImport } from './routes/api.calls.backfill-recording'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api.public.twilio.voice'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api.public.twilio.status'
import { Route as ApiPublicTwilioAmdRouteImport } from './routes/api.public.twilio.amd'
import { Route as ApiPublicPlivoVoiceRouteImport } from './routes/api.public.plivo.voice'
import { Route as ApiPublicPlivoStreamStatusRouteImport } from './routes/api.public.plivo.stream-status'
import { Route as ApiPublicPlivoStatusRouteImport } from './routes/api.public.plivo.status'
import { Route as ApiPublicPlivoRecordingRouteImport } from './routes/api.public.plivo.recording'
import { Route as ApiPublicPlivoAmdRouteImport } from './routes/api.public.plivo.amd'
import { Route as ApiPublicBridgeTimingRouteImport } from './routes/api.public.bridge.timing'
import { Route as ApiPublicBridgeEndRouteImport } from './routes/api.public.bridge.end'
import { Route as ApiPublicAgentTurnStreamRouteImport } from './routes/api.public.agent.turn-stream'
import { Route as ApiPublicAgentTurnRouteImport } from './routes/api.public.agent.turn'
import { Route as ApiPublicAgentTranscriptAppendRouteImport } from './routes/api.public.agent.transcript-append'
import { Route as ApiPublicAgentGreetingRouteImport } from './routes/api.public.agent.greeting'
import { Route as ApiPublicAdminGeneratePreludeSelfRouteImport } from './routes/api.public.admin.generate-prelude-self'
import { Route as ApiPublicAdminGeneratePreludeRouteImport } from './routes/api.public.admin.generate-prelude'
import { Route as ApiPublicAdminGenerateFollowupRouteImport } from './routes/api.public.admin.generate-followup'
import { Route as ApiPublicAdminGenerateCallbackAskRouteImport } from './routes/api.public.admin.generate-callback-ask'
import { Route as ApiCampaignsCampaignIdStopRouteImport } from './routes/api.campaigns.$campaignId.stop'
import { Route as ApiCampaignsCampaignIdSeedRouteImport } from './routes/api.campaigns.$campaignId.seed'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchedulesRoute = DashboardSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOutcomesRoute = DashboardOutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKnowledgeRoute = DashboardKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorsRoute = DashboardDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCallsRoute = DashboardCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsIndexRoute = DashboardPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPatientsRoute,
} as any)
const DashboardCampaignsIndexRoute = DashboardCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCampaignsRoute,
} as any)
const DashboardPatientsListIdRoute = DashboardPatientsListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => DashboardPatientsRoute,
} as any)
const DashboardCampaignsCampaignIdRoute =
  DashboardCampaignsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => DashboardCampaignsRoute,
  } as any)
const ApiHmisSyncRoute = ApiHmisSyncRouteImport.update({
  id: '/api/hmis/sync',
  path: '/api/hmis/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElevenlabsTtsRoute = ApiElevenlabsTtsRouteImport.update({
  id: '/api/elevenlabs/tts',
  path: '/api/elevenlabs/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElevenlabsScribeTokenRoute =
  ApiElevenlabsScribeTokenRouteImport.update({
    id: '/api/elevenlabs/scribe-token',
    path: '/api/elevenlabs/scribe-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCallsStartPlivoRoute = ApiCallsStartPlivoRouteImport.update({
  id: '/api/calls/start-plivo',
  path: '/api/calls/start-plivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsStartRoute = ApiCallsStartRouteImport.update({
  id: '/api/calls/start',
  path: '/api/calls/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsRecordingRoute = ApiCallsRecordingRouteImport.update({
  id: '/api/calls/recording',
  path: '/api/calls/recording',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsHangupRoute = ApiCallsHangupRouteImport.update({
  id: '/api/calls/hangup',
  path: '/api/calls/hangup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsCleanupRoute = ApiCallsCleanupRouteImport.update({
  id: '/api/calls/cleanup',
  path: '/api/calls/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsBridgeStatusRoute = ApiCallsBridgeStatusRouteImport.update({
  id: '/api/calls/bridge-status',
  path: '/api/calls/bridge-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsBackfillRecordingRoute =
  ApiCallsBackfillRecordingRouteImport.update({
    id: '/api/calls/backfill-recording',
    path: '/api/calls/backfill-recording',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio/voice',
  path: '/api/public/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio/status',
  path: '/api/public/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioAmdRoute = ApiPublicTwilioAmdRouteImport.update({
  id: '/api/public/twilio/amd',
  path: '/api/public/twilio/amd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlivoVoiceRoute = ApiPublicPlivoVoiceRouteImport.update({
  id: '/api/public/plivo/voice',
  path: '/api/public/plivo/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlivoStreamStatusRoute =
  ApiPublicPlivoStreamStatusRouteImport.update({
    id: '/api/public/plivo/stream-status',
    path: '/api/public/plivo/stream-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPlivoStatusRoute = ApiPublicPlivoStatusRouteImport.update({
  id: '/api/public/plivo/status',
  path: '/api/public/plivo/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlivoRecordingRoute = ApiPublicPlivoRecordingRouteImport.update({
  id: '/api/public/plivo/recording',
  path: '/api/public/plivo/recording',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlivoAmdRoute = ApiPublicPlivoAmdRouteImport.update({
  id: '/api/public/plivo/amd',
  path: '/api/public/plivo/amd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeTimingRoute = ApiPublicBridgeTimingRouteImport.update({
  id: '/api/public/bridge/timing',
  path: '/api/public/bridge/timing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeEndRoute = ApiPublicBridgeEndRouteImport.update({
  id: '/api/public/bridge/end',
  path: '/api/public/bridge/end',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentTurnStreamRoute =
  ApiPublicAgentTurnStreamRouteImport.update({
    id: '/api/public/agent/turn-stream',
    path: '/api/public/agent/turn-stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentTurnRoute = ApiPublicAgentTurnRouteImport.update({
  id: '/api/public/agent/turn',
  path: '/api/public/agent/turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentTranscriptAppendRoute =
  ApiPublicAgentTranscriptAppendRouteImport.update({
    id: '/api/public/agent/transcript-append',
    path: '/api/public/agent/transcript-append',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentGreetingRoute = ApiPublicAgentGreetingRouteImport.update({
  id: '/api/public/agent/greeting',
  path: '/api/public/agent/greeting',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminGeneratePreludeSelfRoute =
  ApiPublicAdminGeneratePreludeSelfRouteImport.update({
    id: '/api/public/admin/generate-prelude-self',
    path: '/api/public/admin/generate-prelude-self',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminGeneratePreludeRoute =
  ApiPublicAdminGeneratePreludeRouteImport.update({
    id: '/api/public/admin/generate-prelude',
    path: '/api/public/admin/generate-prelude',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminGenerateFollowupRoute =
  ApiPublicAdminGenerateFollowupRouteImport.update({
    id: '/api/public/admin/generate-followup',
    path: '/api/public/admin/generate-followup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminGenerateCallbackAskRoute =
  ApiPublicAdminGenerateCallbackAskRouteImport.update({
    id: '/api/public/admin/generate-callback-ask',
    path: '/api/public/admin/generate-callback-ask',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCampaignsCampaignIdStopRoute =
  ApiCampaignsCampaignIdStopRouteImport.update({
    id: '/api/campaigns/$campaignId/stop',
    path: '/api/campaigns/$campaignId/stop',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCampaignsCampaignIdSeedRoute =
  ApiCampaignsCampaignIdSeedRouteImport.update({
    id: '/api/campaigns/$campaignId/seed',
    path: '/api/campaigns/$campaignId/seed',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/calls': typeof DashboardCallsRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRouteWithChildren
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/outcomes': typeof DashboardOutcomesRoute
  '/dashboard/patients': typeof DashboardPatientsRouteWithChildren
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/calls/backfill-recording': typeof ApiCallsBackfillRecordingRoute
  '/api/calls/bridge-status': typeof ApiCallsBridgeStatusRoute
  '/api/calls/cleanup': typeof ApiCallsCleanupRoute
  '/api/calls/hangup': typeof ApiCallsHangupRoute
  '/api/calls/recording': typeof ApiCallsRecordingRoute
  '/api/calls/start': typeof ApiCallsStartRoute
  '/api/calls/start-plivo': typeof ApiCallsStartPlivoRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
  '/api/elevenlabs/tts': typeof ApiElevenlabsTtsRoute
  '/api/hmis/sync': typeof ApiHmisSyncRoute
  '/dashboard/campaigns/$campaignId': typeof DashboardCampaignsCampaignIdRoute
  '/dashboard/patients/$listId': typeof DashboardPatientsListIdRoute
  '/dashboard/campaigns/': typeof DashboardCampaignsIndexRoute
  '/dashboard/patients/': typeof DashboardPatientsIndexRoute
  '/api/campaigns/$campaignId/seed': typeof ApiCampaignsCampaignIdSeedRoute
  '/api/campaigns/$campaignId/stop': typeof ApiCampaignsCampaignIdStopRoute
  '/api/public/admin/generate-callback-ask': typeof ApiPublicAdminGenerateCallbackAskRoute
  '/api/public/admin/generate-followup': typeof ApiPublicAdminGenerateFollowupRoute
  '/api/public/admin/generate-prelude': typeof ApiPublicAdminGeneratePreludeRoute
  '/api/public/admin/generate-prelude-self': typeof ApiPublicAdminGeneratePreludeSelfRoute
  '/api/public/agent/greeting': typeof ApiPublicAgentGreetingRoute
  '/api/public/agent/transcript-append': typeof ApiPublicAgentTranscriptAppendRoute
  '/api/public/agent/turn': typeof ApiPublicAgentTurnRoute
  '/api/public/agent/turn-stream': typeof ApiPublicAgentTurnStreamRoute
  '/api/public/bridge/end': typeof ApiPublicBridgeEndRoute
  '/api/public/bridge/timing': typeof ApiPublicBridgeTimingRoute
  '/api/public/plivo/amd': typeof ApiPublicPlivoAmdRoute
  '/api/public/plivo/recording': typeof ApiPublicPlivoRecordingRoute
  '/api/public/plivo/status': typeof ApiPublicPlivoStatusRoute
  '/api/public/plivo/stream-status': typeof ApiPublicPlivoStreamStatusRoute
  '/api/public/plivo/voice': typeof ApiPublicPlivoVoiceRoute
  '/api/public/twilio/amd': typeof ApiPublicTwilioAmdRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/calls': typeof DashboardCallsRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/outcomes': typeof DashboardOutcomesRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/calls/backfill-recording': typeof ApiCallsBackfillRecordingRoute
  '/api/calls/bridge-status': typeof ApiCallsBridgeStatusRoute
  '/api/calls/cleanup': typeof ApiCallsCleanupRoute
  '/api/calls/hangup': typeof ApiCallsHangupRoute
  '/api/calls/recording': typeof ApiCallsRecordingRoute
  '/api/calls/start': typeof ApiCallsStartRoute
  '/api/calls/start-plivo': typeof ApiCallsStartPlivoRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
  '/api/elevenlabs/tts': typeof ApiElevenlabsTtsRoute
  '/api/hmis/sync': typeof ApiHmisSyncRoute
  '/dashboard/campaigns/$campaignId': typeof DashboardCampaignsCampaignIdRoute
  '/dashboard/patients/$listId': typeof DashboardPatientsListIdRoute
  '/dashboard/campaigns': typeof DashboardCampaignsIndexRoute
  '/dashboard/patients': typeof DashboardPatientsIndexRoute
  '/api/campaigns/$campaignId/seed': typeof ApiCampaignsCampaignIdSeedRoute
  '/api/campaigns/$campaignId/stop': typeof ApiCampaignsCampaignIdStopRoute
  '/api/public/admin/generate-callback-ask': typeof ApiPublicAdminGenerateCallbackAskRoute
  '/api/public/admin/generate-followup': typeof ApiPublicAdminGenerateFollowupRoute
  '/api/public/admin/generate-prelude': typeof ApiPublicAdminGeneratePreludeRoute
  '/api/public/admin/generate-prelude-self': typeof ApiPublicAdminGeneratePreludeSelfRoute
  '/api/public/agent/greeting': typeof ApiPublicAgentGreetingRoute
  '/api/public/agent/transcript-append': typeof ApiPublicAgentTranscriptAppendRoute
  '/api/public/agent/turn': typeof ApiPublicAgentTurnRoute
  '/api/public/agent/turn-stream': typeof ApiPublicAgentTurnStreamRoute
  '/api/public/bridge/end': typeof ApiPublicBridgeEndRoute
  '/api/public/bridge/timing': typeof ApiPublicBridgeTimingRoute
  '/api/public/plivo/amd': typeof ApiPublicPlivoAmdRoute
  '/api/public/plivo/recording': typeof ApiPublicPlivoRecordingRoute
  '/api/public/plivo/status': typeof ApiPublicPlivoStatusRoute
  '/api/public/plivo/stream-status': typeof ApiPublicPlivoStreamStatusRoute
  '/api/public/plivo/voice': typeof ApiPublicPlivoVoiceRoute
  '/api/public/twilio/amd': typeof ApiPublicTwilioAmdRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/calls': typeof DashboardCallsRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRouteWithChildren
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/outcomes': typeof DashboardOutcomesRoute
  '/dashboard/patients': typeof DashboardPatientsRouteWithChildren
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/calls/backfill-recording': typeof ApiCallsBackfillRecordingRoute
  '/api/calls/bridge-status': typeof ApiCallsBridgeStatusRoute
  '/api/calls/cleanup': typeof ApiCallsCleanupRoute
  '/api/calls/hangup': typeof ApiCallsHangupRoute
  '/api/calls/recording': typeof ApiCallsRecordingRoute
  '/api/calls/start': typeof ApiCallsStartRoute
  '/api/calls/start-plivo': typeof ApiCallsStartPlivoRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
  '/api/elevenlabs/tts': typeof ApiElevenlabsTtsRoute
  '/api/hmis/sync': typeof ApiHmisSyncRoute
  '/dashboard/campaigns/$campaignId': typeof DashboardCampaignsCampaignIdRoute
  '/dashboard/patients/$listId': typeof DashboardPatientsListIdRoute
  '/dashboard/campaigns/': typeof DashboardCampaignsIndexRoute
  '/dashboard/patients/': typeof DashboardPatientsIndexRoute
  '/api/campaigns/$campaignId/seed': typeof ApiCampaignsCampaignIdSeedRoute
  '/api/campaigns/$campaignId/stop': typeof ApiCampaignsCampaignIdStopRoute
  '/api/public/admin/generate-callback-ask': typeof ApiPublicAdminGenerateCallbackAskRoute
  '/api/public/admin/generate-followup': typeof ApiPublicAdminGenerateFollowupRoute
  '/api/public/admin/generate-prelude': typeof ApiPublicAdminGeneratePreludeRoute
  '/api/public/admin/generate-prelude-self': typeof ApiPublicAdminGeneratePreludeSelfRoute
  '/api/public/agent/greeting': typeof ApiPublicAgentGreetingRoute
  '/api/public/agent/transcript-append': typeof ApiPublicAgentTranscriptAppendRoute
  '/api/public/agent/turn': typeof ApiPublicAgentTurnRoute
  '/api/public/agent/turn-stream': typeof ApiPublicAgentTurnStreamRoute
  '/api/public/bridge/end': typeof ApiPublicBridgeEndRoute
  '/api/public/bridge/timing': typeof ApiPublicBridgeTimingRoute
  '/api/public/plivo/amd': typeof ApiPublicPlivoAmdRoute
  '/api/public/plivo/recording': typeof ApiPublicPlivoRecordingRoute
  '/api/public/plivo/status': typeof ApiPublicPlivoStatusRoute
  '/api/public/plivo/stream-status': typeof ApiPublicPlivoStreamStatusRoute
  '/api/public/plivo/voice': typeof ApiPublicPlivoVoiceRoute
  '/api/public/twilio/amd': typeof ApiPublicTwilioAmdRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/calls'
    | '/dashboard/campaigns'
    | '/dashboard/doctors'
    | '/dashboard/knowledge'
    | '/dashboard/outcomes'
    | '/dashboard/patients'
    | '/dashboard/schedules'
    | '/dashboard/'
    | '/api/calls/backfill-recording'
    | '/api/calls/bridge-status'
    | '/api/calls/cleanup'
    | '/api/calls/hangup'
    | '/api/calls/recording'
    | '/api/calls/start'
    | '/api/calls/start-plivo'
    | '/api/elevenlabs/scribe-token'
    | '/api/elevenlabs/tts'
    | '/api/hmis/sync'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/patients/$listId'
    | '/dashboard/campaigns/'
    | '/dashboard/patients/'
    | '/api/campaigns/$campaignId/seed'
    | '/api/campaigns/$campaignId/stop'
    | '/api/public/admin/generate-callback-ask'
    | '/api/public/admin/generate-followup'
    | '/api/public/admin/generate-prelude'
    | '/api/public/admin/generate-prelude-self'
    | '/api/public/agent/greeting'
    | '/api/public/agent/transcript-append'
    | '/api/public/agent/turn'
    | '/api/public/agent/turn-stream'
    | '/api/public/bridge/end'
    | '/api/public/bridge/timing'
    | '/api/public/plivo/amd'
    | '/api/public/plivo/recording'
    | '/api/public/plivo/status'
    | '/api/public/plivo/stream-status'
    | '/api/public/plivo/voice'
    | '/api/public/twilio/amd'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/calls'
    | '/dashboard/doctors'
    | '/dashboard/knowledge'
    | '/dashboard/outcomes'
    | '/dashboard/schedules'
    | '/dashboard'
    | '/api/calls/backfill-recording'
    | '/api/calls/bridge-status'
    | '/api/calls/cleanup'
    | '/api/calls/hangup'
    | '/api/calls/recording'
    | '/api/calls/start'
    | '/api/calls/start-plivo'
    | '/api/elevenlabs/scribe-token'
    | '/api/elevenlabs/tts'
    | '/api/hmis/sync'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/patients/$listId'
    | '/dashboard/campaigns'
    | '/dashboard/patients'
    | '/api/campaigns/$campaignId/seed'
    | '/api/campaigns/$campaignId/stop'
    | '/api/public/admin/generate-callback-ask'
    | '/api/public/admin/generate-followup'
    | '/api/public/admin/generate-prelude'
    | '/api/public/admin/generate-prelude-self'
    | '/api/public/agent/greeting'
    | '/api/public/agent/transcript-append'
    | '/api/public/agent/turn'
    | '/api/public/agent/turn-stream'
    | '/api/public/bridge/end'
    | '/api/public/bridge/timing'
    | '/api/public/plivo/amd'
    | '/api/public/plivo/recording'
    | '/api/public/plivo/status'
    | '/api/public/plivo/stream-status'
    | '/api/public/plivo/voice'
    | '/api/public/twilio/amd'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/calls'
    | '/dashboard/campaigns'
    | '/dashboard/doctors'
    | '/dashboard/knowledge'
    | '/dashboard/outcomes'
    | '/dashboard/patients'
    | '/dashboard/schedules'
    | '/dashboard/'
    | '/api/calls/backfill-recording'
    | '/api/calls/bridge-status'
    | '/api/calls/cleanup'
    | '/api/calls/hangup'
    | '/api/calls/recording'
    | '/api/calls/start'
    | '/api/calls/start-plivo'
    | '/api/elevenlabs/scribe-token'
    | '/api/elevenlabs/tts'
    | '/api/hmis/sync'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/patients/$listId'
    | '/dashboard/campaigns/'
    | '/dashboard/patients/'
    | '/api/campaigns/$campaignId/seed'
    | '/api/campaigns/$campaignId/stop'
    | '/api/public/admin/generate-callback-ask'
    | '/api/public/admin/generate-followup'
    | '/api/public/admin/generate-prelude'
    | '/api/public/admin/generate-prelude-self'
    | '/api/public/agent/greeting'
    | '/api/public/agent/transcript-append'
    | '/api/public/agent/turn'
    | '/api/public/agent/turn-stream'
    | '/api/public/bridge/end'
    | '/api/public/bridge/timing'
    | '/api/public/plivo/amd'
    | '/api/public/plivo/recording'
    | '/api/public/plivo/status'
    | '/api/public/plivo/stream-status'
    | '/api/public/plivo/voice'
    | '/api/public/twilio/amd'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiCallsBackfillRecordingRoute: typeof ApiCallsBackfillRecordingRoute
  ApiCallsBridgeStatusRoute: typeof ApiCallsBridgeStatusRoute
  ApiCallsCleanupRoute: typeof ApiCallsCleanupRoute
  ApiCallsHangupRoute: typeof ApiCallsHangupRoute
  ApiCallsRecordingRoute: typeof ApiCallsRecordingRoute
  ApiCallsStartRoute: typeof ApiCallsStartRoute
  ApiCallsStartPlivoRoute: typeof ApiCallsStartPlivoRoute
  ApiElevenlabsScribeTokenRoute: typeof ApiElevenlabsScribeTokenRoute
  ApiElevenlabsTtsRoute: typeof ApiElevenlabsTtsRoute
  ApiHmisSyncRoute: typeof ApiHmisSyncRoute
  ApiCampaignsCampaignIdSeedRoute: typeof ApiCampaignsCampaignIdSeedRoute
  ApiCampaignsCampaignIdStopRoute: typeof ApiCampaignsCampaignIdStopRoute
  ApiPublicAdminGenerateCallbackAskRoute: typeof ApiPublicAdminGenerateCallbackAskRoute
  ApiPublicAdminGenerateFollowupRoute: typeof ApiPublicAdminGenerateFollowupRoute
  ApiPublicAdminGeneratePreludeRoute: typeof ApiPublicAdminGeneratePreludeRoute
  ApiPublicAdminGeneratePreludeSelfRoute: typeof ApiPublicAdminGeneratePreludeSelfRoute
  ApiPublicAgentGreetingRoute: typeof ApiPublicAgentGreetingRoute
  ApiPublicAgentTranscriptAppendRoute: typeof ApiPublicAgentTranscriptAppendRoute
  ApiPublicAgentTurnRoute: typeof ApiPublicAgentTurnRoute
  ApiPublicAgentTurnStreamRoute: typeof ApiPublicAgentTurnStreamRoute
  ApiPublicBridgeEndRoute: typeof ApiPublicBridgeEndRoute
  ApiPublicBridgeTimingRoute: typeof ApiPublicBridgeTimingRoute
  ApiPublicPlivoAmdRoute: typeof ApiPublicPlivoAmdRoute
  ApiPublicPlivoRecordingRoute: typeof ApiPublicPlivoRecordingRoute
  ApiPublicPlivoStatusRoute: typeof ApiPublicPlivoStatusRoute
  ApiPublicPlivoStreamStatusRoute: typeof ApiPublicPlivoStreamStatusRoute
  ApiPublicPlivoVoiceRoute: typeof ApiPublicPlivoVoiceRoute
  ApiPublicTwilioAmdRoute: typeof ApiPublicTwilioAmdRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedules': {
      id: '/dashboard/schedules'
      path: '/schedules'
      fullPath: '/dashboard/schedules'
      preLoaderRoute: typeof DashboardSchedulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients': {
      id: '/dashboard/patients'
      path: '/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/outcomes': {
      id: '/dashboard/outcomes'
      path: '/outcomes'
      fullPath: '/dashboard/outcomes'
      preLoaderRoute: typeof DashboardOutcomesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/knowledge': {
      id: '/dashboard/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/knowledge'
      preLoaderRoute: typeof DashboardKnowledgeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctors': {
      id: '/dashboard/doctors'
      path: '/doctors'
      fullPath: '/dashboard/doctors'
      preLoaderRoute: typeof DashboardDoctorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calls': {
      id: '/dashboard/calls'
      path: '/calls'
      fullPath: '/dashboard/calls'
      preLoaderRoute: typeof DashboardCallsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/': {
      id: '/dashboard/patients/'
      path: '/'
      fullPath: '/dashboard/patients/'
      preLoaderRoute: typeof DashboardPatientsIndexRouteImport
      parentRoute: typeof DashboardPatientsRoute
    }
    '/dashboard/campaigns/': {
      id: '/dashboard/campaigns/'
      path: '/'
      fullPath: '/dashboard/campaigns/'
      preLoaderRoute: typeof DashboardCampaignsIndexRouteImport
      parentRoute: typeof DashboardCampaignsRoute
    }
    '/dashboard/patients/$listId': {
      id: '/dashboard/patients/$listId'
      path: '/$listId'
      fullPath: '/dashboard/patients/$listId'
      preLoaderRoute: typeof DashboardPatientsListIdRouteImport
      parentRoute: typeof DashboardPatientsRoute
    }
    '/dashboard/campaigns/$campaignId': {
      id: '/dashboard/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/dashboard/campaigns/$campaignId'
      preLoaderRoute: typeof DashboardCampaignsCampaignIdRouteImport
      parentRoute: typeof DashboardCampaignsRoute
    }
    '/api/hmis/sync': {
      id: '/api/hmis/sync'
      path: '/api/hmis/sync'
      fullPath: '/api/hmis/sync'
      preLoaderRoute: typeof ApiHmisSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elevenlabs/tts': {
      id: '/api/elevenlabs/tts'
      path: '/api/elevenlabs/tts'
      fullPath: '/api/elevenlabs/tts'
      preLoaderRoute: typeof ApiElevenlabsTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elevenlabs/scribe-token': {
      id: '/api/elevenlabs/scribe-token'
      path: '/api/elevenlabs/scribe-token'
      fullPath: '/api/elevenlabs/scribe-token'
      preLoaderRoute: typeof ApiElevenlabsScribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/start-plivo': {
      id: '/api/calls/start-plivo'
      path: '/api/calls/start-plivo'
      fullPath: '/api/calls/start-plivo'
      preLoaderRoute: typeof ApiCallsStartPlivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/start': {
      id: '/api/calls/start'
      path: '/api/calls/start'
      fullPath: '/api/calls/start'
      preLoaderRoute: typeof ApiCallsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/recording': {
      id: '/api/calls/recording'
      path: '/api/calls/recording'
      fullPath: '/api/calls/recording'
      preLoaderRoute: typeof ApiCallsRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/hangup': {
      id: '/api/calls/hangup'
      path: '/api/calls/hangup'
      fullPath: '/api/calls/hangup'
      preLoaderRoute: typeof ApiCallsHangupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/cleanup': {
      id: '/api/calls/cleanup'
      path: '/api/calls/cleanup'
      fullPath: '/api/calls/cleanup'
      preLoaderRoute: typeof ApiCallsCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/bridge-status': {
      id: '/api/calls/bridge-status'
      path: '/api/calls/bridge-status'
      fullPath: '/api/calls/bridge-status'
      preLoaderRoute: typeof ApiCallsBridgeStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls/backfill-recording': {
      id: '/api/calls/backfill-recording'
      path: '/api/calls/backfill-recording'
      fullPath: '/api/calls/backfill-recording'
      preLoaderRoute: typeof ApiCallsBackfillRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/voice': {
      id: '/api/public/twilio/voice'
      path: '/api/public/twilio/voice'
      fullPath: '/api/public/twilio/voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/status': {
      id: '/api/public/twilio/status'
      path: '/api/public/twilio/status'
      fullPath: '/api/public/twilio/status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/amd': {
      id: '/api/public/twilio/amd'
      path: '/api/public/twilio/amd'
      fullPath: '/api/public/twilio/amd'
      preLoaderRoute: typeof ApiPublicTwilioAmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plivo/voice': {
      id: '/api/public/plivo/voice'
      path: '/api/public/plivo/voice'
      fullPath: '/api/public/plivo/voice'
      preLoaderRoute: typeof ApiPublicPlivoVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plivo/stream-status': {
      id: '/api/public/plivo/stream-status'
      path: '/api/public/plivo/stream-status'
      fullPath: '/api/public/plivo/stream-status'
      preLoaderRoute: typeof ApiPublicPlivoStreamStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plivo/status': {
      id: '/api/public/plivo/status'
      path: '/api/public/plivo/status'
      fullPath: '/api/public/plivo/status'
      preLoaderRoute: typeof ApiPublicPlivoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plivo/recording': {
      id: '/api/public/plivo/recording'
      path: '/api/public/plivo/recording'
      fullPath: '/api/public/plivo/recording'
      preLoaderRoute: typeof ApiPublicPlivoRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plivo/amd': {
      id: '/api/public/plivo/amd'
      path: '/api/public/plivo/amd'
      fullPath: '/api/public/plivo/amd'
      preLoaderRoute: typeof ApiPublicPlivoAmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/timing': {
      id: '/api/public/bridge/timing'
      path: '/api/public/bridge/timing'
      fullPath: '/api/public/bridge/timing'
      preLoaderRoute: typeof ApiPublicBridgeTimingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/end': {
      id: '/api/public/bridge/end'
      path: '/api/public/bridge/end'
      fullPath: '/api/public/bridge/end'
      preLoaderRoute: typeof ApiPublicBridgeEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/turn-stream': {
      id: '/api/public/agent/turn-stream'
      path: '/api/public/agent/turn-stream'
      fullPath: '/api/public/agent/turn-stream'
      preLoaderRoute: typeof ApiPublicAgentTurnStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/turn': {
      id: '/api/public/agent/turn'
      path: '/api/public/agent/turn'
      fullPath: '/api/public/agent/turn'
      preLoaderRoute: typeof ApiPublicAgentTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/transcript-append': {
      id: '/api/public/agent/transcript-append'
      path: '/api/public/agent/transcript-append'
      fullPath: '/api/public/agent/transcript-append'
      preLoaderRoute: typeof ApiPublicAgentTranscriptAppendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/greeting': {
      id: '/api/public/agent/greeting'
      path: '/api/public/agent/greeting'
      fullPath: '/api/public/agent/greeting'
      preLoaderRoute: typeof ApiPublicAgentGreetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/generate-prelude-self': {
      id: '/api/public/admin/generate-prelude-self'
      path: '/api/public/admin/generate-prelude-self'
      fullPath: '/api/public/admin/generate-prelude-self'
      preLoaderRoute: typeof ApiPublicAdminGeneratePreludeSelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/generate-prelude': {
      id: '/api/public/admin/generate-prelude'
      path: '/api/public/admin/generate-prelude'
      fullPath: '/api/public/admin/generate-prelude'
      preLoaderRoute: typeof ApiPublicAdminGeneratePreludeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/generate-followup': {
      id: '/api/public/admin/generate-followup'
      path: '/api/public/admin/generate-followup'
      fullPath: '/api/public/admin/generate-followup'
      preLoaderRoute: typeof ApiPublicAdminGenerateFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/generate-callback-ask': {
      id: '/api/public/admin/generate-callback-ask'
      path: '/api/public/admin/generate-callback-ask'
      fullPath: '/api/public/admin/generate-callback-ask'
      preLoaderRoute: typeof ApiPublicAdminGenerateCallbackAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/$campaignId/stop': {
      id: '/api/campaigns/$campaignId/stop'
      path: '/api/campaigns/$campaignId/stop'
      fullPath: '/api/campaigns/$campaignId/stop'
      preLoaderRoute: typeof ApiCampaignsCampaignIdStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/$campaignId/seed': {
      id: '/api/campaigns/$campaignId/seed'
      path: '/api/campaigns/$campaignId/seed'
      fullPath: '/api/campaigns/$campaignId/seed'
      preLoaderRoute: typeof ApiCampaignsCampaignIdSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardCampaignsRouteChildren {
  DashboardCampaignsCampaignIdRoute: typeof DashboardCampaignsCampaignIdRoute
  DashboardCampaignsIndexRoute: typeof DashboardCampaignsIndexRoute
}

const DashboardCampaignsRouteChildren: DashboardCampaignsRouteChildren = {
  DashboardCampaignsCampaignIdRoute: DashboardCampaignsCampaignIdRoute,
  DashboardCampaignsIndexRoute: DashboardCampaignsIndexRoute,
}

const DashboardCampaignsRouteWithChildren =
  DashboardCampaignsRoute._addFileChildren(DashboardCampaignsRouteChildren)

interface DashboardPatientsRouteChildren {
  DashboardPatientsListIdRoute: typeof DashboardPatientsListIdRoute
  DashboardPatientsIndexRoute: typeof DashboardPatientsIndexRoute
}

const DashboardPatientsRouteChildren: DashboardPatientsRouteChildren = {
  DashboardPatientsListIdRoute: DashboardPatientsListIdRoute,
  DashboardPatientsIndexRoute: DashboardPatientsIndexRoute,
}

const DashboardPatientsRouteWithChildren =
  DashboardPatientsRoute._addFileChildren(DashboardPatientsRouteChildren)

interface DashboardRouteChildren {
  DashboardCallsRoute: typeof DashboardCallsRoute
  DashboardCampaignsRoute: typeof DashboardCampaignsRouteWithChildren
  DashboardDoctorsRoute: typeof DashboardDoctorsRoute
  DashboardKnowledgeRoute: typeof DashboardKnowledgeRoute
  DashboardOutcomesRoute: typeof DashboardOutcomesRoute
  DashboardPatientsRoute: typeof DashboardPatientsRouteWithChildren
  DashboardSchedulesRoute: typeof DashboardSchedulesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCallsRoute: DashboardCallsRoute,
  DashboardCampaignsRoute: DashboardCampaignsRouteWithChildren,
  DashboardDoctorsRoute: DashboardDoctorsRoute,
  DashboardKnowledgeRoute: DashboardKnowledgeRoute,
  DashboardOutcomesRoute: DashboardOutcomesRoute,
  DashboardPatientsRoute: DashboardPatientsRouteWithChildren,
  DashboardSchedulesRoute: DashboardSchedulesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiCallsBackfillRecordingRoute: ApiCallsBackfillRecordingRoute,
  ApiCallsBridgeStatusRoute: ApiCallsBridgeStatusRoute,
  ApiCallsCleanupRoute: ApiCallsCleanupRoute,
  ApiCallsHangupRoute: ApiCallsHangupRoute,
  ApiCallsRecordingRoute: ApiCallsRecordingRoute,
  ApiCallsStartRoute: ApiCallsStartRoute,
  ApiCallsStartPlivoRoute: ApiCallsStartPlivoRoute,
  ApiElevenlabsScribeTokenRoute: ApiElevenlabsScribeTokenRoute,
  ApiElevenlabsTtsRoute: ApiElevenlabsTtsRoute,
  ApiHmisSyncRoute: ApiHmisSyncRoute,
  ApiCampaignsCampaignIdSeedRoute: ApiCampaignsCampaignIdSeedRoute,
  ApiCampaignsCampaignIdStopRoute: ApiCampaignsCampaignIdStopRoute,
  ApiPublicAdminGenerateCallbackAskRoute:
    ApiPublicAdminGenerateCallbackAskRoute,
  ApiPublicAdminGenerateFollowupRoute: ApiPublicAdminGenerateFollowupRoute,
  ApiPublicAdminGeneratePreludeRoute: ApiPublicAdminGeneratePreludeRoute,
  ApiPublicAdminGeneratePreludeSelfRoute:
    ApiPublicAdminGeneratePreludeSelfRoute,
  ApiPublicAgentGreetingRoute: ApiPublicAgentGreetingRoute,
  ApiPublicAgentTranscriptAppendRoute: ApiPublicAgentTranscriptAppendRoute,
  ApiPublicAgentTurnRoute: ApiPublicAgentTurnRoute,
  ApiPublicAgentTurnStreamRoute: ApiPublicAgentTurnStreamRoute,
  ApiPublicBridgeEndRoute: ApiPublicBridgeEndRoute,
  ApiPublicBridgeTimingRoute: ApiPublicBridgeTimingRoute,
  ApiPublicPlivoAmdRoute: ApiPublicPlivoAmdRoute,
  ApiPublicPlivoRecordingRoute: ApiPublicPlivoRecordingRoute,
  ApiPublicPlivoStatusRoute: ApiPublicPlivoStatusRoute,
  ApiPublicPlivoStreamStatusRoute: ApiPublicPlivoStreamStatusRoute,
  ApiPublicPlivoVoiceRoute: ApiPublicPlivoVoiceRoute,
  ApiPublicTwilioAmdRoute: ApiPublicTwilioAmdRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
